#!/usr/bin/guile \
-s
!#

(use-modules (tuile como))
(use-modules (tuile pr))
(use-modules (tuile utils))
(use-modules (tuile file-path))

(como-command "run_test" "Tero Isannainen" "2025"
    '(
         [single         file     "-f"    "File"]
         ))


(define (run-test test)
  (let ((rf (si "result/#{test}.txt"))
        (gf (si "golden/#{test}.txt")))
    (chdir "test")
    (fps-mkdir-p "result")
    (system (si "gcc -c -Wall -std=gnu99 -g comlin_#{test}.c -o comlin_#{test}.o"))
    (system (si "gcc --coverage -Wall -std=gnu99 -o comlin_#{test} -g comlin_#{test}.o ../build/test/out/test_comlin/comlin.o -lslider"))
    (system (si "rm -f #{rf}; touch #{rf}"))
    (for-each (lambda (cmd)
                (when (not (string-null? cmd))
                  (system (si "echo \"---- CMD: #{cmd}\" >> #{rf}"))
                  (system (si "#{cmd} >> #{rf} 2>&1"))))
              (file->lines (si "test_#{test}")))
    (let ((ret (system (si "diff #{rf} #{gf}"))))
      (chdir "..")
      ret)))

(exit (run-test (como-value "file")))
